### ISSUE TITLE
HomeKit is not working with Cordova Plugin in release mode

### ISSUE THREAD

**Issue by surbhijain1212** [apache/cordova#145] opened 2019-08-07 05:01 UTC
We are developing Hybrid application using Ionic 1 and Angular JS. For HomeKit integration we develop one Cordova plugin. Cordova plugin worked on debug mode but not working in release mode. We are not getting list of homes. Same code is working in native iOS application.

Below are our configuration details: 
Ionic 2.2.3 
Cordova 6.5.0 
Node 6.10.2 
XCode 10.2.1 
iOS 12.3.1 
iOS device iPhone 8+

Could you please guide us to fix this issue.
Thanks in advance

**Comment by breautek** [comment] 2019-10-14 16:42
Support for building your own plugin would probably be better off being asked in our slack community.

http://slack.cordova.io/

**Comment by brodybits** [comment] 2019-12-30 19:11
A [minimal, reproducible example][minimal-reproducible-example] would really be needed to get help with this kind of an issue. Please no Angular or Ionic unless absolutely necessary to reproduce an issue. I would like to close this issue if no [minimal, reproducible example][minimal-reproducible-example] is forthcoming.

[minimal-reproducible-example]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by breautek** [comment] 2020-08-04 23:57
Closing due to lack of response.

**Closed by breautek** 2020-08-04 23:57 UTC
Labels: info-needed, support
