### ISSUE TITLE
Cordova apk returning : the server responded with a non-JavaScript MIME type of ""

### ISSUE THREAD

**Issue by fabrizio03** [apache/cordova#196] opened 2020-02-05 19:45 UTC
I am new with cordova and hybrid apps but I have been trying to fix this problem for a lot.
I'm building an apk using cordova, when I try it as html/css/js I use a simple python script to start a server, but, on android, I get this error when I try to import a js module from html:
`<script type="module">import * as assistantinhelper from './__target__/assistantin.js'; window.assistantinhelper = assistantinhelper;</script>`

I should have installed the latest version of cordova, I'm trying my app on a galaxy A3 2017

I am also using Transcrypt to 'translate' some python scripts to javascript:

```
// Transcrypt'ed from Python, 2020-02-05 19:59:53
import {AssertionError, AttributeError, BaseException, DeprecationWarning, Exception, IndexError, IterableError, KeyError, NotImplementedError, RuntimeWarning, StopIteration, UserWarning, ValueError, Warning, __JsIterator__, __PyIterator__, __Terminal__, __add__, __and__, __call__, __class__, __envir__, __eq__, __floordiv__, __ge__, __get__, __getcm__, __getitem__, __getslice__, __getsm__, __gt__, __i__, __iadd__, __iand__, __idiv__, __ijsmod__, __ilshift__, __imatmul__, __imod__, __imul__, __in__, __init__, __ior__, __ipow__, __irshift__, __isub__, __ixor__, __jsUsePyNext__, __jsmod__, __k__, __kwargtrans__, __le__, __lshift__, __lt__, __matmul__, __mergefields__, __mergekwargtrans__, __mod__, __mul__, __ne__, __neg__, __nest__, __or__, __pow__, __pragma__, __proxy__, __pyUseJsNext__, __rshift__, __setitem__, __setproperty__, __setslice__, __sort__, __specialattrib__, __sub__, __super__, __t__, __terminal__, __truediv__, __withblock__, __xor__, abs, all, any, assert, bool, bytearray, bytes, callable, chr, copy, deepcopy, delattr, dict, dir, divmod, enumerate, filter, float, getattr, hasattr, input, int, isinstance, issubclass, len, list, map, max, min, object, ord, pow, print, property, py_TypeError, py_iter, py_metatype, py_next, py_reversed, py_typeof, range, repr, round, set, setattr, sorted, str, sum, tuple, zip} from './org.transcrypt.__runtime__.js';
var __name__ = '__main__';
export var assistantinkeydown = function (element, event) {
	var key = event.keyCode;
	if (key == 13) {
		element.value = '';
	}
};

//# sourceMappingURL=assistantin.map
```

**Comment by brodybits** [comment] 2020-02-05 19:53
A [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) on most recent Cordova update is needed for this kind of an issue.

Using Transcript sounds really nice but not something we provide direct support for.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Comment by breautek** [comment] 2020-02-05 23:53
`<script type="module">` requires that the file to be served from a http server because because it is forced through the CORS protocol.

It sounds like you are receiving this module from the server, but the provided error suggest that the server is sending an incorrect `Content-Type` header. Ensure that your server is sending the correct mime type for the `Content-Type` header, which should be `text/javascript`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by fabrizio03** [comment] 2020-02-06 16:44
First of all thanks for the answers, and sorry for the late
@brodybits, I added the "transcrypt'ed" file to the post, I hope it can help
@breautek, I know what is the issue about, but I have no idea of how to fix it

**Comment by fabrizio03** [comment] 2020-02-07 18:26
Thank you @brodybits for creating https://github.com/apache/cordova-docs/issues/1054 but I still do not know how to fix this issue, I can still code some other scripts without trying the app on android but I will need to fix soon...

**Comment by brodybits** [comment] 2020-02-07 18:31
Maintainers seem to be a bit overloaded. I would recommend that you follow up with us on Slack or mailing list, follow the links in the footer of cordova.io or cordova.apache.org. We would prefer that people do not ping us by name.

**Comment by jcesarmobile** [comment] 2020-05-05 21:25
If you are loading the files from a server it’s not returning the proper mime type, if you are loading the files from assets then don use module and nomodule as it’s not supported on file protocol.
Closing as this si not really related to cordova.

**Closed by jcesarmobile** 2020-05-05 21:25 UTC
Labels: help wanted, info-needed
