### ISSUE TITLE
Android location permissions not being requested using Cordova 9

### ISSUE THREAD

**Issue by ekrapfl** [apache/cordova#95] opened 2019-04-04 18:17 UTC
# Bug Report

## Problem
I am trying out using Cordova 9, and most things seem to be working alright, but the geolocation plugin is not adding the appropriate `uses-permission` tags to the android manifest file.

Note: this works fine if I revert back `cordova-cli@8` and `cordova-android@7`

### What is expected to happen?
Adding `cordova-plugin-geolocation` should add the appropriate permissions to the manifest file and allow requesting location in the app.
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

### What does actually happen?
Adding `cordova-plugin-geolocation`does not add the appropriate permissions, and thus, my app is not able to request a GPS location.

### Environment, Platform, Device
Android (have not attempted iOS yet)

### Version information
I am using
```
"cordova-plugin-geolocation": "4.0.1"
"cordova-android": "^8.0.0"
"cordova": "^9.0.0"
"ionic": "4.12.0"
```

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

Note: duplicate of this issue, but I thought I would ask here, as it has had no response, and I am making an assumption on where the bug is located.
https://github.com/apache/cordova-plugin-geolocation/issues/147

**Comment by ekrapfl** [comment] 2019-04-17 20:54
Cordova 9 has been out for a little while now.  Has anyone else experienced this issue?  Do you think there is something else going on in my project that could be causing this?  Any assistance would be great, because we would really like to start taking full advantage of that wicked fast prepare speed with Cordova 9 :)

Thanks!

**Comment by raphinesse** [comment] 2019-04-17 22:10
@dpogue Do you think that could be connected to the config munge changes too?

**Comment by dpogue** [comment] 2019-04-17 22:26
It's certainly possible...

**Comment by ekrapfl** [comment] 2019-04-28 20:54
Any traction on this?  I still have not heard if anyone else is experiencing anything like this, but it happens every time for me.  No location permissions are added for Android, which makes my app in particular a brick ☹️

**Comment by raphinesse** [comment] 2019-04-29 17:46
Could you provide copy-pasteable shell commands to reproduce this issue? Or a MWE if it's more complex? That could increase the chance of someone confirming this. Sorry for having you wait.

**Comment by ekrapfl** [comment] 2019-04-29 19:49
Yeah, sorry I should have narrowed this down sooner.  Basically, I just started with a simple `cordova create`.
Here is the package.json I am using:
```
{
  "main": "index.js",
  "dependencies": {
    "cordova": "^9.0.0",
    "cordova-android": "^8.0.0",
    "cordova-plugin-geolocation": "4.0.1"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

And here is the config.xml:
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>Hello</description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">hello</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <plugin name="cordova-plugin-geolocation" spec="4.0.1" />
    <platform name="android">
        <allow-intent href="market:*" />
        <!-- <config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
        </config-file> -->
    </platform>
    <engine name="android" spec="^7.1.4" />
</widget>
```

If you leave that line commented out and run an `npx cordova prepare`, you will see that the generated `platforms/android/app/src/AndroidManifest.xml` will have the proper location permissions:
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-feature android:name="android.hardware.location.gps" />
```

If you uncomment the lines in the config.xml, however, and re-run your `npx cordova prepare`, it will remove those permissions.

It is worth noting that I do see the following warning on prepare:
```
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
```
However, I have always seen that warning, so I thought nothing of it when upgrading to Cordova 9.  Using Cordova 8, I saw that warning, but it still had all of the permissions in the AndroidManifest file.  It may very well be that I should be requesting camera permission in a different way than what I am attempting to do here, because it is clearly not allowing both the way I am specifying and the way the plugin wants to use.  What am I doing wrong?

Thanks,
Eben

**Comment by ekrapfl** [comment] 2019-04-29 20:38
Seems to me that sometimes, plugins specify permissions, but sometimes they don't.  I can specify them with a `<config-file>`, but doing so should not overwrite the permissions specified by plugins I have added, right?

**Comment by raphinesse** [comment] 2019-04-29 20:44
> Seems to me that sometimes, plugins specify permissions, but sometimes they don't. I can specify them with a `<config-file>`, but doing so should not overwrite the permissions specified by plugins I have added, right?

Agreed. I'll try to see if I can reproduce your issue. But from first glance, it does _not_ look like it's your fault.

**Comment by dpogue** [comment] 2019-04-29 21:00
This sounds exactly like https://github.com/apache/cordova-cli/issues/389 and https://github.com/apache/cordova-android/issues/704

**Comment by raphinesse** [comment] 2019-04-29 21:13
@ekrapfl I can reproduce the issue. @dpogue Thanks for linking these issues. Would be great if @knight9999 could look into this. I actually have zero knowledge of the whole `ConfigChanges` code in `cordova-common`.

**Comment by cyparu** [comment] 2019-05-05 21:40
After upgrading to **Cordova 9.0.0 & Cordova-Android 8.0.0** I also reproducibly experienced a similar problem were the otherwise correctly generated Android Manifest file under **platforms/android/app/src/main/AndroidManifest.xml** was corrupted during **'cordova prepare'** phase. The actual changes (manifest "corruption") consisted in removing several **uses-permission** and **uses-features** tags from the initially correct manifest:
```xml 
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
```
After digging a lot to find a solution to avoid this annoying behavior, I ended up with a final work-around where I used a Cordova hook for **before_prepare** & **after_prepare** that will backup & restore the correct manifest. 

Until an official fix/update will be provided, here is the hook that I've implemented, hoping to be useful for others encountering this bug. 
Please note the hook (to be removed when the bug is fixed!) is implemented into a single JavaScript file (**hooks/android_manifest_fixer.js**) covering both events being registered under **config.xml** as follows:

```xml
<hook type="before_prepare" src="hooks/android_manifest_fixer.js"/>
<hook type="after_prepare" src="hooks/android_manifest_fixer.js"/>
```

Below I included the relevant **hooks/android_manifest_fixer.js** JavaScript code that will backup & restore the manifest where the new created files (**AndroidManifest.xml.good** + **AndroidManifest.xml.bad**) are saved directly under **app** root folder (outside the **src** path) to avoid being included into Android app build processing.

```java
"use strict";

/* eslint-env node */
var fs = require("fs"),
	utils = require("./utils"),
	colors = utils.colors,
	log = utils.log;

// hook function
function hook(context) {
	var manifestPath = "./platforms/android/app/src/main/AndroidManifest.xml",
		manifestPathGood = "./platforms/android/app/AndroidManifest.xml.good",
		read = function(file) {
			return fs.readFileSync(file, "utf8");
		},
		write = function(file, str) {
			return fs.writeFileSync(file, str, "utf8");
		},
		copy = function(source, dest) {
			write(dest, read(source));
		};
	if (context.hook === "before_prepare") {
		// backup the manifest
		log("Backup 'AndroidManifest.xml' as " + colors.yellow(manifestPathGood));
		copy(manifestPath, manifestPathGood);
	} else if (context.hook === "after_prepare") {
		var manifestText = read(manifestPath),
			manifestTextGood = read(manifestPathGood),
			manifestPathBad = "./platforms/android/app/AndroidManifest.xml.bad";
		// check if the the manifest was changed during preparation
		if (manifestText !== manifestTextGood) {
			log("Save corrupted 'AndroidManifest.xml' under " +	colors.yellow(manifestPathBad));
			write(manifestPathBad, manifestText);
			log("Restore 'AndroidManifest.xml' from " + colors.yellow(manifestPathGood));
			write(manifestPath, manifestTextGood);
		} else {
			log("The AndroidManifest.xml is not modified during prepare " + colors.red(" -> The 'android_manifest_fixer' hook is NOT needed anymore !"));
		}
	}
}

// export hook function
module.exports = hook;
```

**Comment by ekrapfl** [comment] 2019-05-06 13:13
Thanks for the workaround!  I was going to give it a shot, but I might need the functions you are importing from `./utils`.  Unless I am missing something there :)

Thanks again!

**Comment by cyparu** [comment] 2019-05-06 15:49
> 
> 
> Thanks for the workaround, @cyparu! I was going to give it a shot, but I might need the functions you are importing from `./utils`. Unless I am missing something there :)
> 
> Thanks again!

The `utils` module includes some project dependent functions but you can safely remove/neglect them (colors + log exported functions) or just replace the full imports with:
```javascript
var fs = require("fs"),
	colors = require("chalk"),
	log = console.log;
``` 

With this small code change, hopefully the provided work-around will 🚀 for you as well 👍

**Comment by ekrapfl** [comment] 2019-05-06 16:23
That does not appear to be working for me, but I am really holding out hope for the true solution here, anyway.  I'm glad you have found a workaround that works for you, though!

**Comment by cyparu** [comment] 2019-05-06 17:38
> 
> 
> That does not appear to be working for me, but I am really holding out hope for the true solution here, anyway. I'm glad you have found a workaround that works for you, though!

Did you've properly registered the hook under config.xml ? Check this link ( https://cordova.apache.org/docs/en/9.x/guide/appdev/hooks/#configxml )  for additional info on how to use the Cordova hooks.

If you are running `cordova prepare|build android --verbose` ( see: https://cordova.apache.org/docs/en/9.x/reference/cordova-cli/index.html#project-command-list ) you should see more info related to hook executions and if everything works fine you should also find the 2 generated files **(AndroidManifest.xml.good + AndroidManifest.xml.bad)** are saved directly under **platforms/android/app** folder

**Comment by ekrapfl** [comment] 2019-05-06 17:44
Yes, I added the hook, and it was running.  It was erroring out if I do not have an existing AndroidManifest.xml (ie: first time prepare).  It did not error out when I ran a `cordova platform add android` instead of the prepare (just trying to hit it from a different angle), but in that case, it gave me an AndroidManifest.xml that had even more stripped out of it.  I saw that it generated the `.good` and `.bad`, but neither of them was the one that I would have expected.  The `.bad` was the one that I have previously been getting from `cordova prepare` (makes sense), but the `.good` was an even more stripped down version.  It had less than what the previous one did.

**Comment by cyparu** [comment] 2019-05-07 07:19
> 
> 
> Yes, I added the hook, and it was running. It was erroring out if I do not have an existing AndroidManifest.xml (ie: first time prepare). It did not error out when I ran a `cordova platform add android` instead of the prepare (just trying to hit it from a different angle), but in that case, it gave me an AndroidManifest.xml that had even more stripped out of it. I saw that it generated the `.good` and `.bad`, but neither of them was the one that I would have expected. The `.bad` was the one that I have previously been getting from `cordova prepare` (makes sense), but the `.good` was an even more stripped down version. It had less than what the previous one did.

@ekrapfl Sorry to hear that my workaround doesn't work for you 😟 
Since the prepare hooks are also triggered whenever the cordova project is created or a platform will be added to make sure the fixer backup/restore ones are executed just after `cordova build` is started, I've added a another hook (`before_build`) that will just set a flag `inBuildPhase` (otherwise false) that can be used as a guard for this special condition. See the snippets below:

**config.xml** updates:

```xml
<hook type="before_build" src="hooks/android_manifest_fixer.js"/>
<hook type="before_prepare" src="hooks/android_manifest_fixer.js"/>
<hook type="after_prepare" src="hooks/android_manifest_fixer.js"/> 
```
**android_manifest_fixer.js** updates:

```javascript
"use strict";

/* eslint-env node */
var fs = require("fs"),
	colors = require("chalk"),
	log = console.log,
	inBuildPhase = false; 

// hook function
function hook(context) {
	var manifestPath = "./platforms/android/app/src/main/AndroidManifest.xml",
		manifestPathGood = "./platforms/android/app/AndroidManifest.xml.good",
		read = function(file) {
			return fs.readFileSync(file, "utf8");
		},
		write = function(file, str) {
			return fs.writeFileSync(file, str, "utf8");
		},
		copy = function(source, dest) {
			write(dest, read(source));
		};
	if (!inBuildPhase) { // enable the fixed just in build 
	 	if  (context.hook === "before_build") {
			// flag the build phase
			log("Enter build phase, enable the fixer!");
			inBuildPhase = true
	 	}
	} else if (context.hook === "before_prepare") {
		// backup the manifest
		log("Backup 'AndroidManifest.xml' as " + colors.yellow(manifestPathGood));
		copy(manifestPath, manifestPathGood);
	} else if (context.hook === "after_prepare") {
		var manifestText = read(manifestPath),
			manifestTextGood = read(manifestPathGood),
			manifestPathBad = "./platforms/android/app/AndroidManifest.xml.bad";
		// check if the the manifest was changed during preparation
		if (manifestText !== manifestTextGood) {
			log("Save corrupted 'AndroidManifest.xml' under " +	colors.yellow(manifestPathBad));
			write(manifestPathBad, manifestText);
			log("Restore 'AndroidManifest.xml' from " + colors.yellow(manifestPathGood));
			write(manifestPath, manifestTextGood);
		} else {
			log("The AndroidManifest.xml is not modified during prepare " + colors.red(" -> The 'android_manifest_fixer' hook is NOT needed anymore !"));
		}
	}
}

// export hook function
module.exports = hook;
```

As the manifest corruption is happening just during pre-build prepare , I hope this enhanced handling will better isolate the problem and preserve the proper manifest.

**Comment by ekrapfl** [comment] 2019-05-13 12:39
Okay, so using your new script, if I start completely fresh (nuke node_modules, platforms, and plugins), do an `npm install`, and then run `cordova prepare`, then `cordova build android`, I end up with no difference from what I had before adding the hook.  Still missing some of the permissions.

Again, I don't necessarily need the workaround for now, I am just hoping for a fix.  Any news on that front @knight9999 or @raphinesse?

**Comment by ekrapfl** [comment] 2019-06-03 19:01
@raphinesse is there any update to share on this?  I know some other issues were mentioned as potentially related.  Unfortunately, this is still completely blocking us from using Cordova 9 and its amazingly fast prepare speeds :(

**Comment by raphinesse** [comment] 2019-06-03 19:48
Unfortunately there is no progress on this that I know of. I understand that this is a serious problem. I just had a personal friend tell me that he's affected by it too. As I stated above, unfortunately I myself am not acquainted with the code responsible for the config changes.

It has been suggested that the bug might be caused by https://github.com/apache/cordova-common/pull/24. So if you should want to take action yourself, you could go ahead and try if reverting that change fixes the bug for you.

**Comment by ekrapfl** [comment] 2019-06-14 11:48
@raphinesse Is there anyone else who could be poked to look into it?  I know dpogue said he has no time for Cordova at the moment, and you are unfamiliar with the area.  I have reached out to the original author of the PR in question, and he has not responded.  I would love to be able to help on this, but I have looked over the code from that PR, and I am completely clueless on what I would do to fix it.  I apologize for being so persistent on this issue, but as you said, it is a serious problem, so I want to make sure I am exhausting all of my options to get it resolved.

Thanks again!

**Comment by raphinesse** [comment] 2019-06-14 22:33
@erisu can you free up something for this? If the aforementioned PR is really the culprit, would it be feasible to revert it? Better to have broken uninstalls than installs IMHO.

@ekrapfl can you verify that it works when using the latest version of cordova-common with the changes from the PR reverted?

**Comment by ekrapfl** [comment] 2019-06-15 14:29
I can give that a shot next week and let you know if it works for me.

**Comment by knight9999** [comment] 2019-06-17 04:22
@raphinesse Thanks you for responding the issue.
And sorry. As all you mentioned, there are some problems.

Basically, my PR https://github.com/apache/cordova-common/pull/24 is aiming to correct counting
in the munge section in platform.json.

This does not permit the conflicting of config-file/edit-config strictly.
When conflicting happens between config.xml and plugin.xml, the config.xml has priority and used.
Even if the conflicting is solvable.

As a result, the user must describe all permissions in config.xml if the user want to use additional permission which conflict to plugin.xml.

For example,
```
<config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> 
            <uses-feature android:name="android.hardware.location.gps" />
</config-file>
```

**Comment by ekrapfl** [comment] 2019-06-17 12:53
@raphinesse I can confirm that reverting that PR does fix the issue for me.
@knight9999 I suppose a valid work around for the time being could be to take on the config-file additions from our plugins, but that doesn't seem like a permanent solution.  If plugins specify their own config dependencies, why should I have to duplicate what they have already said they need?

Thanks!

**Comment by knight9999** [comment] 2019-06-18 03:44
@ekrapfl  Thank a lot for the reporting. 
Yes, I agree your opinion.

But anyway, the current situation in cordova config.xml/plugin.xml system is very complicated.

Because users can always edit their config.xml and add/remove plugins in any order.
Some config.xml/plugin.xml may conflict each other.
One more difficulty is how to recover the setting files when the plugin is removed if it was merged in complicated way.
The other difficulty is how to distinguish which settings are already applied, which settings are not yet applied and then which settings are merged in what way when the users edit his config.xml.

I think the `munge` system builtin cordova is a good system to resolve them, but it may be not enough.

I image that the bi-directional system (add <-> remove,  edit <-> recover, merge <-> unmerge are possible) is too difficult.
I think that the one-way system (it always generates settings files from the original files by applying each patch) is more simple even if there is still conflict problem.

**Comment by gartorware** [comment] 2019-06-19 13:13
> Okay, so using your new script, if I start completely fresh (nuke node_modules, platforms, and plugins), do an `npm install`, and then run `cordova prepare`, then `cordova build android`, I end up with no difference from what I had before adding the hook. Still missing some of the permissions.
> 
> Again, I don't necessarily need the workaround for now, I am just hoping for a fix. Any news on that front @knight9999 or @raphinesse?

The problem here is that cordova@9 generates a wrong manifest even while removing/adding platform from scratch.

I have managed to use the workaround suggested (btw, thank you very much @cyparu) by downgrading cordova to version 8, removing android platform, adding it again (AndroidManifest.xml is correct on this point), uninstalling cordova 8, installing cordova 9.

BTW, facing this issue on several projects. Not only for third party plugins, but for own edit-config tags. I cannot use my own network_security_config, which used to work on cordova 8 (this edit-config is default on ionic):
```
    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
```

**Comment by knight9999** [comment] 2019-06-27 08:23
@gartorware Does your issue still exist?
I have tried your config.xml
```
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
```
without any plugin.

**Comment by gartorware** [comment] 2019-06-29 10:50
Yeah, without any plugins it may work. But when some plugin add their own `edit-config` or `config-file` cordova mess up the final AndroidManifest.xml. Even if those `edit-config` are not related to each other still issues arises.

Lately, I'm facing issues even with cordova-8 now. I have a plugin which add tons of new lines to AndroidManifest.xml by using config-file. Then this xml-security edit-config mess it up, dropping sequential lines from resulting AndroidManifest.xml on each build. I mean, it drops a (random?) line when I build, lets say L50. I restore that dropped line, then on next build it drops L51.

**Comment by knight9999** [comment] 2019-07-07 04:44
@gartorware Thanks. I think the typical situation in which i can reproduce this issue is follwoing.

**Comment by knight9999** [comment] 2019-07-07 05:10
This happens because both `edit-config` in `config.xml` and  `config-file` in `plugin.xml` are going to update the same `application` directive in `AndroidManifest.xml` and then they conflict. 
The logic in `cordova-common` can not resolve this conflict and apply the only one which takes high priority.

So we should introduce the logic to solve this kind of conflict programatically.

**Comment by knight9999** [comment] 2019-07-07 05:19
If we resolved conflict, there is another difficulty.
1) If we remove `edit-config` directive in `config.xml`, the `AndroidManifext.xml` should be back to the previous one. 
2) If we remove `camera` plugin, the `AndroidManifest.xml` should become to the one in which only `edit-config` in `config.xml` is applied.

**Closed** 2019-08-21 03:23 UTC
Labels: bug

**Comment by bandhavya** [comment] 2019-10-23 01:23
Im facing this issue after upgrading to cordova 9.0.0 with cordova android 8.0.0
This issue seems to be solved in this post.
Can I know how to get these changes

**Comment by StephanBijzitter** [comment] 2021-03-01 14:42
I still seem to have this issue with Cordova 10
