### ISSUE TITLE
Cordova corrupt my node_module

### ISSUE THREAD

**Issue by dfa1234** [apache/cordova#138] opened 2019-07-09 14:56 UTC
# Bug Report

#### Problem

Cordova corrupt my node_module everytime I launch a command.
It's very annoying
I have to to `npm i` between all steps.

I will update later a perfect description to reproduce if you need. But I don't understand how it is possible, anyone has the same problem?? I tried on mac and ubuntu, same thing.

#### Information
[to be edited]

#### Command or Code
[to be edited]

#### Environment, Platform, Device
[to be edited]

### Version information
[to be edited]

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by raphinesse** [comment] 2019-07-09 15:16
Do you use the `--no-save`option? It is broken and might be the cause for the described behavior.

**Comment by dfa1234** [comment] 2019-07-09 15:30
no, I don't use it. I use Ionic also, but I'm 100% that it's the result of cordova commands (I test these command alone)

**Comment by brodybits** [comment] 2019-07-15 21:09
Is there any that we can reproduce this issue?

**Comment by dfa1234** [comment] 2019-07-16 17:36
Hard to say. I should try with a blank project.

Right now for exemple I made

`cordova build ios --device`

And right after, when I want to complie my code with webpack

`
Cannot find module 'tslib'
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
...
`

But It's 100% sure it's not webpack the problem

**Comment by breautek** [comment] 2019-10-14 16:56
Generally speaking, when I get weird behaviours such as these, I have to do:

```bash
rm -rf node_modules
rm package-lock.json
npm install
```

The issue for me usually comes from weird stale stuff where `package-lock.json` doesn't actually reflect updates in `package.json`

**Comment by raphinesse** [comment] 2019-11-26 17:40
Closing as reproduction case has not been provided.

**Closed by raphinesse** 2019-11-26 17:40 UTC
Labels: info-needed, support
