### ISSUE TITLE
cordova-android-11 build error

### ISSUE THREAD

**Issue by AdrianArribas** [apache/cordova#341] opened 2022-09-06 06:49 UTC
# Bug Report

Hi.
Currently in my project we are trying to migrate from cordova-android-10 to cordova-android-11, unfortunately during the compilation we received a compilation error that we have not been able to determine its origin, we believe it may be a cordova bug.

We are using: 
Cordova 10.1.0
Angular 12
Ionic 5.3
Gradle 7.4
Android SDK 32

`1: Task failed with an exception.
-----------
* Where:
Script '/Users/myuser/myapp/platforms/android/cordova-plugin-badge/app-badge.gradle' line: 28

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [me.leolin:ShortcutBadger:1.1.22@aar] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
Command failed with exit code 1: /Users/myuser/myapp/platforms/android/gradlew cdvBuildDebug -b /Users/myuser/myapp/platforms/android/build.gradle
[ERROR] An error occurred while running subprocess cordova.`

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment] 2022-09-06 13:03
The issue is inside a third-party plugin, cordova-plugin-badge

It's because in it's gradle file it includes, it is using `compile` which has been deprecated by Gradle for some time now. Plugins that uses gradle should use `implementation` instead.

In it's tagged release, https://github.com/katzer/cordova-plugin-badge/blob/0.8.8/src/android/badge.gradle#L28 it still uses `compile`, but it is resolved in their master branch @ https://github.com/katzer/cordova-plugin-badge/blob/master/src/android/badge.gradle#L28

You'll have to ask the plugin maintainers to make a release.

Closing as it's not a bug with Cordova.

**Closed by breautek** 2022-09-06 13:03 UTC
