### ISSUE TITLE
Loading cordova.js in a web worker and use a bluetooth plugin to process in a different thread

### ISSUE THREAD

**Issue by alejo-0204** [apache/cordova#93] opened 2019-04-02 22:08 UTC
# Loading cordova.js in a web worker and use a bluetooth plugin to process in a different thread

Hi! I'm trying to connect a bluetooth printer and say "Hello". I'm using **cordova-plugin-bluetooth-serial**.
The main problem is because a worker can't manipulate the DOM or windows, so the console show the next error when execute the command **cordova run android --device**:

    cordova.js:2184 Uncaught ReferenceError: window is not defined
    at cordova.js:2184
    at cordova.js:2189
    at demo_workers.js:1

Is there a way to load cordova.js in a worker and be able to load plugins to work isolated from the main thread?

# Code to replicate the situation:

## package json:
**package.json** 

    {
    "name": "com.test",
    "displayName": "test",
    "version": "1.0.0",
    "description": "A sample Apache Cordova application.",
    "main": "index.js",
    "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "Apache Cordova Team",
    "license": "Apache-2.0",
    "dependencies": {
    "cordova-android": "^7.1.4",
    "cordova-plugin-bluetooth-serial": "^0.4.7",
    "cordova-plugin-whitelist": "^1.3.3"
    },
    "cordova": {
    "plugins": {
    "cordova-plugin-whitelist": {},
    "cordova-plugin-bluetooth-serial": {}
    },
    "platforms": ["android"]
    }
    }

## /www files:

**index.html**

    <!DOCTYPE  html>
    <html>
    <script  type="text/javascript"  src="setupWorker.js"></script>
    <script  type="text/javascript">
	    function  print() {
		    w.postMessage("Hello");
	    }
    </script>
    <body>
	    <button  onclick="print()">print</button>
	    <div  id="statusDiv"></div>
    </body>
    </html>
**setupWorker.js**

    var  w;
    function  startWorker() {
	    if (typeof  Worker  !==  "undefined") {
		    if (typeof  w  ==  "undefined") {
			    w  =  new  Worker("demo_workers.js");
		    }
	    } else {
		    document.getElementById("statusDiv").innerHTML  =
		    "Sorry! No Web Worker support.";
	    }
    }
    startWorker();
**demo_workers.js**

    importScripts("cordova.js");
    importScripts("bluetooth.js");
      
    app.initialize(); 
    onmessage  =  function(e) {
    	app.onMessage(e.data);
    };

**bluetooth.js**

    var  macAddress  =  "00:00:00:00:00:00";
    
    var  app  = {
	    initialize:  function() {
		    this.bindEvents();
	    },
	    bindEvents:  function() {
		    self.addEventListener("deviceready", this.onDeviceReady, false);
	    },
	    onDeviceReady:  function() {
		    bluetoothSerial.connect(macAddress, app.onConnect, app.onDisconnect);
	    },
	    onConnect:  function() {
		    console.log("Connected to "  +  macAddress  +  ".");
		    bluetoothSerial.subscribe("\n", app.onMessage, app.subscribeFailed);
	    },
	    onDisconnect:  function() {
		    console.log("Disconnected.");
	    },
	    onMessage:  function(data) {
		    bluetoothSerial.write(
			    data,
			    () => { console.log("write succsess");},
			    () => {console.log("write dailure");}
		    );
	    },
	    subscribeFailed:  function() {
		    console.log("subscribeFailed...");
	    }
    };

**Comment by raphinesse** [comment] 2019-04-03 08:58
Interesting scenario IMHO. At least all platform-independent code of `cordova-js` only uses `window` to access global variables AFAICT. So you could throw in a `const window = self;` at the very top of your `demo_workers.js` and see what happens.

**Comment by alejo-0204** [comment] 2019-04-03 12:35
Thanks @raphinesse, 
I found a example of your suggested approach before, when I modify **demo_workers.js** and run the application, works (no warnings), but the problem is that i realize that have to handle all the possibles scenarios and situations, that means a lot of possible failure scenarios and not standard approach. I would like to found a solution that don't involves recreate the DOM and window.

After the below implementation cordova.js show this message:

`cordova.js:1945 Could not find cordova.js script tag. Plugin loading may fail.`

Because it is expecting to get **/cordova.js** when call **document.getElementsByTagName('script');**

And it is necessary to fire the event **deviceready** that means create the logic for  **document.dispatchEvent** `cordova.js:227`

# /www files:

**demo_workers.js**
```
self.window = self;
self.window.Event = function() {};
self.window.prompt = function() {};
self.window.innerHeight = 1;
self.history = {};
self.document = {
  readyState: "complete",
  addEventListener: function() {},
  querySelector: function() {},
  getElementsByTagName: function() {
    return [];
  },
  createElement: function() {
    return {
      pathname: "",
      setAttribute: function() {}
    };
  },
  createEvent: function() {
    return {
      initEvent: function() {}
    };
  },
  documentElement: {
    style: {
      transition: ""
    }
  },
  head: {
    children: [],
    appendChild: function(child) {
      importScripts(child.src);
      child.onload();
    }
  },
  body: {
    classList: {
      add: function() {}
    }
  },
  dispatchEvent: () => {}
};

importScripts("cordova.js");
importScripts("bluetooth.js");

app.initialize();

onmessage = function(e) {
  app.onMessage(e.data);
};
```

**Comment by janpio** [comment] 2019-04-10 17:25
@alejo-0204 That is how Cordova works in that regard, so recreating the functionality it needs but is missing in a web worker seems like a valid approach to solve this problem.

**Comment by raphinesse** [comment] 2019-04-10 18:10
@alejo-0204 If you are interested in improving the web worker compatibility of cordova-js, feel free to open a PR over there. I guess at least some of the patching you had to do could be avoided with fairly small changes. (Like not relying on `window` as the global object)

**Comment by brodybits** [comment] 2019-05-10 20:33
Also a functional sample demo or starter project would help anyone else who needs to do something similar.

**Comment by mzielezny** [comment] 2020-02-16 19:01
@alejo-0204 
Have you maybe tried to run solution on Android device ?
I have tried with multiple plugins and I have impression that on browser based plugins everything is working fine, but on Android device overload of window.prompt is not working. No event (even failure) is noticed on the java portion of cordova code.  
Maybe someone other have an idea how to force android to detect overload method ?

**Comment by brodybits** [comment] 2020-02-16 19:03
cordova.js was never designed to work in a web worker; it just happens to work on browser, not expected to work on other platforms such as Android or iOS

**Comment by Vetagiri-Hrushikesh** [comment] 2022-01-13 12:44
> Interesting scenario IMHO. At least all platform-independent code of `cordova-js` only uses `window` to access global variables AFAICT. So you could throw in a `const window = self;` at the very top of your `demo_workers.js` and see what happens.

After trying what you said.
```"Uncaught ReferenceError: window is not defined"``` 
How to solve this issue? 
Are there any other ways to call our plugin API inside web worker?

**Comment by breautek** [comment] 2022-05-18 04:18
Cordova does not support web workers.

The webview itself supports web workers, but the bridge API to communicate between the webview and native is on the "main" JS thread.

Currently there are no plans on implementing support for a Cordova API in web workers. If having web worker support so that you can communicate with native plugins via web worker is desirable, I'd suggest opening a Feature Request issue describing the use case.

Closing as not a bug / won't fix.

**Closed by breautek** 2022-05-18 04:18 UTC
Labels: support
