### ISSUE TITLE
Unable to add platform for the plugin which is created using plugman

### ISSUE THREAD

**Issue by parasappafluke** [apache/cordova#87] opened 2019-03-27 15:19 UTC
# Bug Report
Unable to add platform for the plugin which is created using plugman.
## Problem
I have created a plugin using below command and the plugin was created successfully.

plugman create --name <pluginName> --plugin_id <pluginID> --plugin_version <version> [--path <directory>] [--variable NAME=VALUE]

But when i try to add a platform with below command, it fails.

plugman platform add --platform_name ios

### What is expected to happen?

It should add platform details to plugin.xml file which is created from the previous step.

### What does actually happen?
I got error on Terminal saying
"(node:6361) UnhandledPromiseRejectionWarning: Error: platform: true not yet supported"

## Information

(node:6361) UnhandledPromiseRejectionWarning: Error: platform: true not yet supported
    at Object.add (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platform.js:51:35)
    at Object.module.exports [as platform] (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/platform_operation.js:23:38)
    at Object.platform (/usr/local/lib/node_modules/plugman/node_modules/cordova-lib/src/plugman/plugman.js:153:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/plugman/main.js:87:42)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
(node:6361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Command or Code

plugman platform add --platform_name ios

### Environment, Platform, Device

OS: Mac OS X 10.14.1

### Version information

Cordova: 9.0.0
Plugman: 3.0.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by janpio** [comment] 2019-03-27 16:10
Duplicate of https://github.com/apache/cordova/issues/88

**Closed** 2019-03-27 16:10 UTC
