### ISSUE TITLE
TypeError: Failed To fetch after building the application with quasar

### ISSUE THREAD

**Issue by NouhToulali1997** [apache/cordova#338] opened 2022-07-27 16:25 UTC
# Bug Report

## Problem

application can't hit the api defined on a local server with http after build.
error returned: TypeError: Failed To fetch

But, while dev the application (quasar dev -m cordova -T android) everything works good.

**Comment by breautek** [comment] 2022-07-27 16:40
I'm just guessing because your bug report lacks a lot of details but Android applications by default will refuse to connect to non-secure servers (e.g. non https) in release mode. Debug modes, SSL validation is relaxed. For deployments your servers should be deployed with valid/up-to-date SSL.

If this doesn't solve your issue and you believe there is still a bug within the Cordova Android platform, then I'd suggest raising an issue in the [cordova-android](https://github.com/apache/cordova-android/issues) repository. Note that failing to provide adequate information as requested in the issue form may result in the issue being closed without a resolution.

Additionally, if you're using any kind of third-party build tool or framework such as quasar, it will be worth while reproducing the issue in a simple pure cordova application to eliminate any possibility that the issue is within the third-party build tool/frameworks. Cordova volunteers are likely to skip over issues that doesn't have issues isolated. You can read more on how to build a good [reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) for making bug reports.

Closing as invalid due to significant portion of the issue form missing.

**Closed by breautek** 2022-07-27 16:40 UTC
