### ISSUE TITLE
Loading chunk 0 failed

### ISSUE THREAD

**Issue by Manjucloudmpower** [apache/cordova#122] opened 2019-06-08 17:39 UTC
# Bug Report
The cordova app often fails to load the webview saying Loading chunk x failed.
It happens very rarely though. Not sure if it is related to cordova or webpack. 
This bug is random in nature and cant be reproducible.

Most of the users have been facing this issue and yet there is no working solution.

### What is the expected behaviour
Chunks should be loaded without error as all the chunks are present. 

### Environment, Platform, Device

Cordova any version
Both android and ios
Webpack: 4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment] 2019-06-11 08:35
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by raphinesse** [comment] 2019-11-26 17:44
Closing as requested reproduction case has not been provided. Also this seems to be a webpack issue not related to cordova

**Closed by raphinesse** 2019-11-26 17:44 UTC
Labels: support
