### ISSUE TITLE
CordovaError: TypeError: Cannot assign to read only property 'valueOf' of object '[object Object]'

### ISSUE THREAD

**Issue by domschmidt** [apache/cordova#260] opened 2020-11-25 17:16 UTC
Using the following package
"cordova": "10.0.0"

the following error occurs. 
Please see the full log (verbose flag has been set):
```

"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run ionic-build-windows-dev --scripts-prepend-node-path=auto --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'ionic-build-windows-dev',
npm verb cli   '--scripts-prepend-node-path=auto',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.0.3
npm info using node@v15.0.1
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:C:\workspace\trampolin-mobile-test\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\Domin\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\Domin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 14ms
npm timing config:load:setEnvs Completed in 6ms
npm timing config:load Completed in 28ms
npm verb npm-session 21d594f9f8069e48
npm timing npm:load Completed in 78ms
[..................] \ : timing npm:load Completed in 78ms
> trampolin-mobile@1.1.0 ionic-build-windows-dev
> ionic cordova build windows --confirm --no-interactive -- --arch=x86

√ Creating .\www directory for you in 1.10mspleted in 78ms
--confirm: Platform windows is not installed! Would you like to install it? Yes
> cordova.cmd platform add windows --saveCompleted in 78ms
Using cordova-fetch for cordova-windows@7.0.1leted in 78ms
Failed to fetch platform cordova-windows@7.0.1eted in 78ms
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: TypeError: Cannot assign to read only property 'valueOf' of object '[object Object]'
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add windows --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
npm timing command:run-script Completed in 4988ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:327:20)
npm verb stack     at maybeClose (node:internal/child_process:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm verb pkgid trampolin-mobile@1.1.0
npm verb cwd C:\workspace\trampolin-mobile-test
npm verb Windows_NT 10.0.19041
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic-build-windows-dev" "--scripts-prepend-node-path=auto" "--verbose"
npm verb node v15.0.1
npm verb npm  v7.0.3
npm ERR! code 1
npm ERR! path C:\workspace\trampolin-mobile-test
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "ionic cordova build windows --confirm --no-interactive -- --arch=x86"
npm verb exit 1
npm timing npm Completed in 5397ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Domin\AppData\Local\npm-cache\_logs\2020-11-25T17_13_00_191Z-debug.log

```

Once I deleted the folders
 - www
 - platforms
 - plugins

and rolled back the cordova dependency to version "9.0.0", the error is gone.

Most probably this is a side effect of any dependency used in cordova 10.0.0 lib

**Comment by raphinesse** [comment] 2020-11-25 17:24
Duplicate of https://github.com/apache/cordova-cli/issues/543

**Closed by raphinesse** 2020-11-25 17:24 UTC
