### ISSUE TITLE
Can't build anymore on Cordova after activating iOS app group and service notification extension

### ISSUE THREAD

**Issue by jay34fr** [apache/cordova#129] opened 2019-06-21 11:15 UTC
Hi all,

I have a mobile application under : 
- Cordova 8.1.2. 
- iOS platform 5.0.0 
- onesignal-cordova-plugin 2.4.7 
- Xcode 10.2.1

Everything was ok. Building &co.

Then I tried to activate the iOS Service notification extension in order to have Media Attachments.

I followed these docs from OneSignal (in this order) : 
- https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend- 
- https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup

Everything was ok. I was able to launch the app from Xcode and the Media attachments tests were OK.

But then I try to build again my app in CLI and I have the issue : 
CordovaError: Could not find *-Info.plist file, or config.xml file.

I think Xcode changed some parameter but I can't figure what...

If you have any idea, it will be really appreciated.

Thx in advance for your help.

**Comment by brodybits** [comment] 2019-07-15 21:00
This looks like an issue with the OneSignal SDK plugin, wonder if you should [raise an issue there](https://github.com/onesignal/OneSignal-Cordova-SDK/issues).

In case you think this is an issue with Cordova, a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would really be appreciated (see [this guide](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) for more details).

We would also highly recommend you upgrade to Cordova CLI version 9 as we do not support old versions.

**Comment by Aarbel** [comment] 2019-08-13 09:07
@jay34fr have you found a way to fix it ?
Have you also found a way to set up onesignal with only Cordova settings ? 
Where do you work in France ? Could be great to share about it ! my Linkedin => https://www.linkedin.com/in/cl%E9ment-fradet-normand-65607a65

**Comment by raphinesse** [comment] 2019-11-26 17:42
Closing as requested reproduction case has not been provided.

**Closed by raphinesse** 2019-11-26 17:42 UTC
Labels: support
