### ISSUE TITLE
Video files (native HTML 5 video element) within iframe will not go into full screen when user taps the full screen icon

### ISSUE THREAD

**Issue by bar8s** [apache/cordova#416] opened 2023-06-27 08:32 UTC
# Bug Report

## Problem
Video files (native HTML 5 video element) will not go into fullscreen when user taps the fullscreen icon in the video element controls.
Issue seems to be related to Android only.
The fullscreen icon is visible and is not visibly disabled.
Video will play and all other controls work as expected.
Fullscreen functionality does work as expected when HTML content (including video) is displayed in a standard web browser.
Issue only occurs when HTML is displayed via an iFrame in the cordova app.
allowfullscreen=true added to parent iFrame. 
Discounted any dom element overlaying fullscreen control.
It is possible to fullscreen a video once during a users app session.
An app restart is required to allow full screen of a video again.

### What is expected to happen?

When a video is exposed via the video element the full screen icon should trigger the video to show in full screen mode when the content is embedded within an iframe

### What does actually happen?

The first time a video is displayed within a session, all works fine, but after that any other videos fail to react to the full screen icon, an app restart is required to allow full screen of a video again.

## Information

The following  post seems to talk about the same issue, but has no resolution
https://stackoverflow.com/questions/75953598/android-cordova-html5-video-fullscreen-only-works-on-first-instance

### Environment, Platform, Device
Android 

### Version information
Cordova 11
React based web app

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2024-03-12 12:02
duplicate of https://github.com/apache/cordova-android/issues/1560

**Closed by jcesarmobile** 2024-03-12 12:02 UTC
