### ISSUE TITLE
cordova-ios 6.0.0 launchstoryboard white

### ISSUE THREAD

**Issue by barakataboujreich** [apache/cordova#220] opened 2020-06-25 12:11 UTC
hello guys,
we recently moved to ios 6.0.0, one of the changes switch from legacy launch images to story board images.
we created the images according to the dimensions given in the documentation
[launch storyboard images at cordova website](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#launch-storyboard-images)

and added the following to config.xml

```
<splash src="res/screen/ios/Default@2x~iphone~anyany.png" />
    <splash src="res/screen/ios/Default@2x~iphone~comany.png" />
    <splash src="res/screen/ios/Default@2x~iphone~comcom.png" />
    <splash src="res/screen/ios/Default@3x~iphone~anyany.png" />
    <splash src="res/screen/ios/Default@3x~iphone~anycom.png" />
    <splash src="res/screen/ios/Default@3x~iphone~comany.png" />
    <splash src="res/screen/ios/Default@2x~ipad~anyany.png" />
    <splash src="res/screen/ios/Default@2x~ipad~comany.png" />
```

then ran the following command

`cordova prepare ios`

opened xcode, and navigated to Images.xcassets then LaunchStoryboard and saw the images.

then on the iphone x running ios 13.5.1 deleted the app to prevent cashing as mentioned.
run the app, but all i got is a white screen and then the app continue normally. 

i thought the problem was with photos, so i created one blue photo with dimensions 2732x2732
added `<splash src="res/screen/ios/Default@2x~universal~anyany.png" />` to config.xml and removed the others.

then ran

`cordova prepare ios`

opened xcode, and navigated to Images.xcassets then LaunchStoryboard and saw the blue image and the others removed.

but the same thing happened again, just white screen not my image.

i deleted the app every time i needed to install.
cleaned the build folder.
tried on the simulator with no use.

can anyone tell me what i am doing wrong ?
cordova: 9.0.0
cordova-ios: 9.0.0 (cordova-lib@9.0.1)

device running on:
iphone x, ios 13.5.1

**Comment by timbru31** [comment] 2020-06-25 12:41
This is probably a duplicate of https://github.com/apache/cordova-ios/issues/890 - please update to v6.1.0 and try again. If the issue persists, open a new issue in https://github.com/apache/cordova-ios instead. Make sure to fill in the issue template, otherwise we can't help. Thanks!

**Closed by timbru31** 2020-06-25 12:41 UTC
